config/routes.rb
Rails.application.routes.draw do
  root 'calculators#new'
  resources :calculators
  delete '/calculators', to: 'calculators#clear_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculator.rb
class Calculator < ApplicationRecord
  before_save :get_total

  validates :principle, presence: true, numericality: true
  validates :year, presence: true, numericality: true
  validates :rate, presence: true, numericality: true

  def get_total
    self.total = principle * ( 1 +((rate/100) * year))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  def new
    @calculator = Calculator.new
  end

  def index
    @calculator = Calculator.all
  end

  def create
    @calculator = Calculator.create(calculator_params)
    if @calculator.save
      redirect_to calculator_path(@calculator), notice: "Calculation successful!"
    else
      render :new
    end
  end

  def show
    @calculator = Calculator.find(params[:id])
  end

  def destroy
    @calculator = Calculator.find(params[:id])
    @calculator.destroy
    redirect_to root_path, notice: "Record deleted"
  end

  def clear_list
    @calculator = Calculator.all
    @calculator.destroy_all
    redirect_to root_path, notice: "All records deleted"
  end

  private
    def calculator_params
      params.require(:calculator).permit(:year, :principle, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>History</h1>

<table>
  <thead>
    <tr>
      <th>Years</th>
      <th>Principal</th>
      <th>Rate</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calculator.each do |calculator| %>
      <tr>
        <td><%= calculator.year %></td>
        <td><%= calculator.principle %></td>
        <td><%= calculator.rate %></td>
        <td><%= calculator.total %></td>
        <td><%= link_to 'Show', calculator %></td>
        <td><%= link_to 'Destroy', calculator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Calculate', root_path %>
<%= link_to 'Delete All', calculators_path, method: :delete, data: {confirm: 'Are you sure you want to delete all records?'} %>

app/views/calculators/new.html.erb
<p id="notice"><%= notice %></p>

<% if @calculator.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@calculator.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @calculator.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= link_to 'History', calculators_path %>

<%= form_with scope: :calculator, url: calculators_path, local: true do |f| %>
  <p>
  <%= f.label :principle %>
  <%= f.text_field :principle %>
  </p>
  <p>
  <%= f.label :rate %>
  <%= f.text_field :rate %>
  </p>
  <p>
  <%= f.label :year %>
  <%= f.text_field :year %>
  </p>
  <p><%= f.submit 'Calculate' %></p>
<% end %>

app/views/calculators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Years:</strong>
  <%= @calculator.year %>
</p>

<p>
  <strong>Principal:</strong>
  <%= @calculator.principle %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @calculator.rate %>
</p>

<p>
  <strong>Total:</strong>
  <%= @calculator.total %>
</p>

<%= link_to 'Back', calculators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>